---
version: 2
project_name: docfresh
archives:
  - name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    files:
      - LICENSE
      - README.md
      - third_party_licenses/**/*
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
builds:
  - binary: docfresh
    main: cmd/docfresh/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
release:
  prerelease: "true"
  header: |
    [Pull Requests](https://github.com/suzuki-shunsuke/docfresh/pulls?q=is%3Apr+milestone%3A{{.Tag}}) | [Issues](https://github.com/suzuki-shunsuke/docfresh/issues?q=is%3Aissue+milestone%3A{{.Tag}}) | https://github.com/suzuki-shunsuke/docfresh/compare/{{.PreviousTag}}...{{.Tag}}

sboms:
  - id: default
    disable: false

homebrew_casks:
  - repository:
      owner: suzuki-shunsuke
      name: homebrew-docfresh
    # The project name and current git tag are used in the format string.
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: https://github.com/suzuki-shunsuke/docfresh
    description: Create GitHub App User Access Token for secure local development
    license: MIT
    skip_upload: true
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/docfresh"]
          end

scoops:
  -
    description: |
      Create GitHub App User Access Token for secure local development
    license: MIT
    skip_upload: true
    repository:
      owner: suzuki-shunsuke
      name: scoop-bucket
